Lesson1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('',include('home.urls')),
    path('admin/' , admin.site.urls) ,
    path('house/',include('house.urls')),
    path('home/',include('home.urls')),
    path('user/',include('user.urls')),
    path('content/',include('content.urls')),
    path('ckeditor/' , include('ckeditor_uploader.urls')) ,
    path('home/' , include('home.urls')) ,


    path('hakkimizda/',views.hakkimizda,name='hakkimizda'),
    path('category/<slug:slug>/<int:id>/',views.category_ilanlar,name='category_ilanlar'),
    path('houses/<slug:slug>/<int:id>/',views.UrunSayfasi,name='UrunSayfasi'),
    path('search/',views.house_search,name='house_search'),
    path('search2/',views.house_search2 ,name='house_search2'),
    path('search_auto/',views.house_search_auto,name='house_search_auto'),


    path('logout/',views.logout_view,name='logout_view'),
    path('login/',views.login_view,name='login_view'),
    path('signup/',views.signup_view,name='signup_view'),
    path('sss/',views.faq,name='faq'),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home /
    path('', views.index, name='index'),

]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home /
    path('', views.index, name='index'),
    path('ilanlar',views.ilanlar, name='ilanlar'),
    path('iletisim',views.iletisim, name='iletisim'),


]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    adress = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtserver = models.CharField(blank=True,max_length=20)
    smtemail = models.CharField(blank=True,max_length=20)
    smtpassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    website = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height=50"/>'.format(self.icon.url))
        image_tag.short_description = 'Image'


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed','Closed')
    )

    name = models.CharField(blank=True,max_length=20)
    email = models.CharField(blank=True, max_length=50)
    icon = models.ImageField(blank=True, upload_to='images/')
    subject = models.CharField(blank=True,max_length=50)
    message = models.CharField(blank=True,max_length=255)
    ip = models.CharField(blank=True,max_length=50)
    note = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactFormu(ModelForm):
    class Meta:
        model=ContactFormMessage
        fields = ['name','email','subject','message']
        widgets ={
            'name' : TextInput(attrs={'class': 'input','placeholder':'İsim Soyisim'}),
            'subject' : TextInput(attrs={'class': 'input','placeholder':'Konu'}),
            'email' : TextInput(attrs={'class': 'input','placeholder':'Email adresi'}),
            'message' : Textarea(attrs={'class': 'input','placeholder':'Mesajınız','rows':'5'}),


        }

class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    adress = models.CharField(blank=True , max_length=150)
    phone = models.CharField(blank=True , max_length=15)
    city = models.CharField(blank=True , max_length=15)
    country = models.CharField(blank=True , max_length=15)
    image = models.ImageField(blank=True , upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return '['+self.user.username+'] '+self.user.first_name+' '+self.user.last_name

    def image_tag(self):
        return mark_safe('<img src="{}" height=50"/>'.format(self.image.url))
        image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
        class Meta:
            model = UserProfile
            fields = ['phone', 'adress', 'city', 'country','image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber=models.IntegerField()
    question = models.CharField(max_length=155)
    answer   = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

house/models.py
import sys

from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True' , 'Evet') ,
        ('False' , 'Hayır') ,
    )

    title = models.CharField(max_length=90)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    listeleme = models.IntegerField(default=0)
    image = models.ImageField(blank=True , upload_to='images/')
    status = models.CharField(max_length=10 , choices=STATUS)
    slug = models.SlugField(null=False , unique=True)
    parent = TreeForeignKey('self' , blank=True , null=True , related_name='children' , on_delete=models.CASCADE)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return '/'.join(full_path[::-1])
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail' , kwargs={'slug': self.slug})

class housefav(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    house=models.ForeignKey("House",on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

class House(models.Model):
    STATUS = (
        ('True' , 'Evet') ,
        ('False' , 'Hayır') ,

    )
    Kredi = (
        ('True' , 'Evet') ,
        ('False' , 'Hayır') ,

    )
    takas = (
        ('True' , 'Evet') ,
        ('False' , 'Hayır') ,

    )
    Esya = (
        ('Esyali' , 'Esyali') ,
        ('Esyasiz' , 'Esyasiz') ,

    )
    kullanim = (
        ('Bos' , 'Bos') ,
        ('Dolu' , 'Dolu') ,
    )
    kimden = (
        ('Sahibinden' , 'Sahibinden') ,
        ('Emlak' , 'Emlak') ,
    )
    cephe = (
        ('Güney' , 'Güney') ,
        ('Kuzey' , 'Kuzey') ,
    )
    binatipler = (
        ('Kerpiç Bina' , 'Kerpiç Bina') ,
        ('Ahşap Bina' , 'Ahşap Bina') ,
        ('Yarı Kagir Bina' , 'Yarı Kagir Bina') ,
        ('Kagir Bina' , 'Kagir Bina') ,
        ('Betonarme Bina' , 'Betonarme Bina') ,
        ('Çelik  Bina' , 'Çelik  Bina') ,
    )
    tapu = (
        ('Kat mülkiyetli tapu' , 'Kat mülkiyetli tapu') ,
        ('Kat irtifaklı tapu' , 'Kat irtifaklı tapu') ,
        ('Hisseli tapu' , 'Hisseli tapu') ,

    )
    Cities = (
        ('1' , 'Adana') ,
        ('2' , 'Adıyaman') ,
        ('3' , 'Afyonkarahisar') ,
        ('4' , 'Ağrı ') ,
        ('5' , 'Amasya ') ,
        ('6' , 'Ankara ') ,
        ('7' , 'Antalya ') ,
        ('8' , 'Artvin ') ,
        ('9' , 'Aydın ') ,
        ('10' , 'Balıkesir') ,
        ('11' , 'Bilecik ') ,
        ('12' , 'Bingöl ') ,
        ('13' , 'Bitlis ') ,
        ('14' , 'Bolu ') ,
        ('15' , 'Burdur ') ,
        ('16' , 'Bursa ') ,
        ('17' , 'Çanakkale') ,
        ('18' , 'Çankırı ') ,
        ('19' , 'Çorum ') ,
        ('20' , 'Denizli ') ,
        ('21' , 'Diyarbakır ') ,
        ('22' , 'Edirne ') ,
        ('23' , 'Elazığ ') ,
        ('24' , 'Erzincan ') ,
        ('25' , 'Erzurum ') ,
        ('26' , 'Eskişehir ') ,
        ('27' , 'Gaziantep ') ,
        ('28' , 'Giresun ') ,
        ('29' , 'Gümüşhane ') ,
        ('30' , 'Hakkâri ') ,
        ('31' , 'Hatay ') ,
        ('32' , 'Isparta ') ,
        ('33' , 'Mersin ') ,
        ('34' , 'İstanbul ') ,
        ('35' , 'İzmir ') ,
        ('59' , 'Tekirdağ') ,
        ('60' , 'Tokat ') ,
        ('61' , 'Trabzon ') ,
        ('62' , 'Tunceli ') ,
        ('63' , 'Şanlıurfa ') ,
        ('64' , 'Uşak ') ,
        ('65' , 'Van ') ,
        ('66' , 'Yozgat') ,
        ('67' , 'Zonguldak') ,
        ('68' , 'Aksaray ') ,
        ('69' , 'Bayburt ') ,
        ('70' , 'Karaman ') ,
        ('71' , 'Kırıkkale ') ,
        ('72' , 'Batman ') ,
        ('73' , 'Şırnak ') ,
        ('74' , 'Bartın ') ,
        ('75' , 'Ardahan ') ,
        ('76' , 'Iğdır ') ,
        ('77' , 'Yalova ') ,
        ('78' , 'Karabük ') ,
        ('79' , 'Kilis ') ,
        ('80' , 'Osmaniye') ,
        ('81' , 'Düzce ') ,
        ('82','Diğer')
    )

    category = models.ForeignKey(Category , on_delete=models.CASCADE)
    userOwner = models.ForeignKey(User , on_delete=models.CASCADE , default=0)
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    kimden = models.CharField(max_length=20,choices=kimden,default="Sahibinden")
    image = models.ImageField(blank=True , upload_to='images/')
    price = models.IntegerField(blank=True , default=0)
    aidat = models.IntegerField(blank=True , default=0)
    buildTime = models.IntegerField(blank=True , default=0)
    kat = models.IntegerField(blank=True,default=0)
    isinmatip = models.CharField(max_length=255,blank=True)
    katsayisi = models.IntegerField(blank=True,default=0)
    KrediUygun = models.CharField(max_length=10 , choices=Kredi,default="Hayır")
    esyaDurum = models.CharField(max_length=10 , choices=Esya,default="Esyasiz")
    yapiTipi = models.CharField(max_length=25, choices=binatipler,default="Betonarme Bina")
    kullanimDurumu = models.CharField(max_length=10,choices=kullanim,default="bos")
    tapuDurumu = models.CharField(max_length=30,choices=tapu,default="Kat irtifaklı tapu")
    takas = models.CharField(max_length=10,choices=takas,default="Hayir")
    cephe = models.CharField(max_length=20,choices=cephe,default="Güney")
    description = models.CharField(max_length=255,blank=True)
    area = models.IntegerField(blank=True , default=0)
    bedroom = models.IntegerField(blank=True , default=0)
    bathroom = models.IntegerField(blank=True , default=0)
    garage = models.IntegerField(blank=True , default=0)
    slug = models.SlugField(null=False , unique=True)
    locationDetail = models.CharField(max_length=150 , default="-")
    city = models.CharField(max_length=50 , choices=Cities)
    district = models.CharField(max_length=70 , default="-")
    detail = RichTextUploadingField()
    status = models.CharField(max_length=10 , choices=STATUS)
    favorite= models.ManyToManyField(User,related_name='favorite',blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height=50"/>'.format(self.image.url))
        image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('house_detail' , kwargs={'slug': self.slug})




class Images(models.Model):
    house = models.ForeignKey(House , on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = models.ImageField(blank=True , upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height=50"/>'.format(self.image.url))
        image_tag.short_description = 'Image'

class HouseImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title','image']



class Comment(models.Model):
    STATUS = (
        ('New' , 'Yeni') ,
        ('True' , 'Evet') ,
        ('False' , 'Hayır') ,
    )
    house = models.ForeignKey(House , on_delete=models.CASCADE)
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    subject = models.CharField(max_length=50 , blank=True)
    comment = models.TextField(max_length=255 , blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10 , choices=STATUS , default='New')
    ip = models.CharField(blank=True , max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject' , 'comment' , 'rate']

class CImages(models.Model):
    house=models.ForeignKey(House,on_delete=models.CASCADE)
    title=models.CharField(max_length=50,blank=True)
    image=models.ImageField(blank=True,upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src"{}" height="50"/>'.format(self.image.url))
    image_tag.short_description='Image'

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search' , max_length=100)
    catid = forms.IntegerField()
    cityid = forms.IntegerField()
    priceid = forms.IntegerField()


class SearchForm2(forms.Form):
    query2 = forms.CharField(label='Search2' , max_length=100)
    catid2 = forms.IntegerField()
    cityid2 = forms.IntegerField()
    minbedid = forms.IntegerField()
    districtid = forms.CharField(label='ilce' , max_length=100)
    minbathid = forms.IntegerField()
    minpriceid = forms.IntegerField()
    maxpriceid = forms.IntegerField()
    minareaid = forms.IntegerField()
    maxareaid = forms.IntegerField()



class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30,label='User Name :')
    email = forms.EmailField(max_length=200,label='Email :')
    first_name = forms.CharField(max_length=100 , help_text='First Name',label='First Name :')
    last_name = forms.CharField(max_length=100 , help_text='Last Name',label='Last Name :')

    class Meta:
        model = User
        fields = ('username' , 'email' , 'first_name' , 'last_name' , 'password1' , 'password2' ,)

content/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return HttpResponse("Hello Content")

home/templates/faq.html
{% extends "homebase.html" %}

{% block title %}Sıkça Sorulan Sorular {% endblock %}
{% block keywords %} Sıkça Sorulan Sorular anahtar kelimeler {% endblock %}
{% block description %} Sıkça Sorulan <Sorular></Sorular> açıklama {% endblock %}

{% block head %}
        <script>
  $( function() {
    $( "#accordion" ).accordion();
  } );
  </script>
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block baslik %}
    {% include "baslik.html" %}
    {% block link %} iletisim {% endblock %}
{% endblock %}

{% block body %}
    {% load static %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_4.jpg' %}');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <h1 class="mb-2 bread">Sıkça Sorulan Sorular</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="/">KonutAL <i class="ion-ios-arrow-forward"></i></a></span>
                        <span class="mr-2"></span> <span>Sıkça Sorulan Sorular<i class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section contact-section">
        <div class="container">

            <div id="accordion">
              {% for rs in faq %}
            <h3>{{ rs.question }}</h3>
            <div>
                <p>
                   {{ rs.answer|safe }}
                </p>
            </div>
            {% endfor %}
        </div>
        </div>
    </section>

{% endblock %}

home/templates/ilanlar.html
{% extends "homebase.html" %}

{% block title %} İlanlar {% endblock %}
{% block keywords %} {{ categorydata.keywords }} {% endblock %}
{% block description %} {{ categorydata.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block content %}
    {% load static %}
    {% load humanize %}


    <div class="col-lg-9">

        <h5 class="mr-2"><a href="/ilanlar">İlanlar</a>
            {% if categorydata.parent %}
                       / <a href="/category/{{ categorydata.parent.slug }}/{{ categorydata.parent.id }}">{{ categorydata.parent.title }}</a>/
            {% endif %}
            /<a href="/category/{{ categorydata.slug }}/{{ categorydata.id }}">{{ categorydata.title }}</a>
        </h5>
        <div class="row">

            <!-- İlanların Çekilmesi -->
            {% if not houses %}
                <div class="col-md-12 col-lg-12 ftco-animate">
                    <h1>Eşleşen bir ilan Bulunamadı </h1>
                </div>

            {% else %}
                {% for rs in houses %}
                    <div class="col-md-6 col-lg-4 ftco-animate">
                        <div class="project">
                            <div class="img">
                                <img src="{{ rs.image.url }}" class="img-fluid" alt="Colorlib Template">
                                <div class="text"> <h3><a href="/houses/{{ rs.slug }}/{{ rs.id }}">{{ rs.title }}</a></h3>
                                </div>
                            </div>
                            <div class="desc pt-3">
                                <h4 class="price">{{ rs.price|intcomma }} ₺</h4>
                                <p class="h-info"><span class="location">{{ rs.district }}</span> <span
                                        class="details">&mdash;{{ rs.get_city_display }}     </span></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                </div>
		    		</div>
		    		<div class="row no-gutters my-5">
		          <div class="col text-center">
		            <div class="block-27">
		              <ul>
		                <li><a href="#">&lt;</a></li>
		                <li class="active"><span>1</span></li>
		                <li><a href="#">2</a></li>
		                <li><a href="#">3</a></li>
		                <li><a href="#">4</a></li>
		                <li><a href="#">5</a></li>
		                <li><a href="#">&gt;</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
    </div>
    </div>
    </div>
    </section>
{% endblock %}

home/templates/iletisim.html
{% extends "homebase.html" %}

{% block title %} İletisim Sayfası {% endblock %}
{% block keywords %} İletisim Sayfası anahtar kelimeler {% endblock %}
{% block description %} İletisim Sayfası açıklama {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block baslik %}
    {% include "baslik.html" %}
    {% block link %} iletisim {% endblock %}
{% endblock %}

{% block body %}
    {% load static %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_4.jpg' %}');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <h1 class="mb-2 bread">İletisim</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="/">KonutAL <i class="ion-ios-arrow-forward"></i></a></span>
                        <span class="mr-2"></span> <span>İletisim<i class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section contact-section">
        <div class="container">
            <div class="row d-flex contact-info">
                <div class="col-md-3 d-flex">
                    <div class="bg-light align-self-stretch box p-4 text-center">
                        <h3 class="mb-4">Addres</h3>
                        <p>{{setting.adress}}</p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="bg-light align-self-stretch box p-4 text-center">
                        <h3 class="mb-4">İletişim Numarası</h3>
                        <p><a href="tel://1234567920">{{setting.phone}}</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="bg-light align-self-stretch box p-4 text-center">
                        <h3 class="mb-4">Email Adresi</h3>
                        <p><a href="mailto:info@yoursite.com">{{setting.email}}</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="bg-light align-self-stretch box p-4 text-center">
                        <h3 class="mb-4">Website</h3>
                        <p><a href="#">{{setting.website}}</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
        <div class="container">
            <div class="row d-flex align-items-stretch no-gutters">
                <div class="col-md-6 p-4 p-md-5 order-md-last bg-light">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" rpşe="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <!- İletisim Formu Gönderme Bölümü -!>
                    <form action="" method="post">
                        {% csrf_token %}


                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your Name" name="name" id="id_name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your Email" name="email" id="id_email">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Subject" name="subject"
                                   id="id_subject">
                        </div>
                        <div class="form-group">
                            <textarea name="message" id="id_message" cols="30" rows="7" class="form-control"
                                      placeholder="Message"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>
                </div>
                <div class="col-md-6 d-flex align-items-stretch">
                    <div id="map"></div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

home/templates/index.html
{% extends "homebase.html" %}

{% block title %} {{ setting.title }} {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block description %} {{ setting.description }}  {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block slider %}
    {% include "slider.html" %}
{% endblock %}

{% block body %}
    {% load static %}
    <section class="ftco-section ftco-no-pb">
        <div class="container">
            <div class="row justify-content-start mb-5">
                <div class="col-md-8 heading-section ftco-animate">
                    <h2 class="mb-4">Yeni Eklenenler</h2>
                    <p>Yeni Eklenen evleri aşağıdaki slider yardımıyla bulabilirsiniz.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="carousel-properties owl-carousel">
                        {% for rs in yeniEklenenler %}
                            <div class="item">
                                <div class="project">
                                    <div class="img">
                                        <img src="{{ rs.image.url }}" class="img-fluid" alt="Colorlib Template"
                                             style="height: 200px">
                                        <div class="text">
                                            <span>Sale</span>
                                            <h3><a href="/houses/{{ rs.slug }}/{{ rs.id }}">{{ rs.title }}</a></h3>
                                        </div>
                                    </div>
                                    <div class="desc pt-3">
                                        <h4 class="price">{{ rs.price }}</h4>
                                        <p class="h-info"><span class="location">{{ rs.get_city_display  }}</span> <span
                                                class="details">&mdash; {{ rs.district }}</span></p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
    </section>


{% endblock %}