Lesson1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('',include('home.urls')),
    path('admin/' , admin.site.urls) ,
    path('house/',include('house.urls')),
    path('home/',include('home.urls')),
    path('user/',include('user.urls')),
    path('content/',include('content.urls')),
    path('ckeditor/' , include('ckeditor_uploader.urls')) ,
    path('home/' , include('home.urls')) ,


    path('hakkimizda/',views.hakkimizda,name='hakkimizda'),
    path('category/<slug:slug>/<int:id>/',views.category_ilanlar,name='category_ilanlar'),
    path('houses/<slug:slug>/<int:id>/',views.UrunSayfasi,name='UrunSayfasi'),
    path('search/',views.house_search,name='house_search'),
    path('search2/',views.house_search2 ,name='house_search2'),
    path('search_auto/',views.house_search_auto,name='house_search_auto'),


    path('logout/',views.logout_view,name='logout_view'),
    path('login/',views.login_view,name='login_view'),
    path('signup/',views.signup_view,name='signup_view'),
    path('sss/',views.faq,name='faq'),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home /
    path('', views.index, name='index'),
    path('ilanlar',views.ilanlar, name='ilanlar'),
    path('iletisim',views.iletisim, name='iletisim'),


]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home /
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addhouse/',views.addhouse,name='addhouse'),
    path('myhouses/',views.myhouses,name='myhouses'),
    path('houseedit/<int:id>',views.houseedit,name='houseedit'),
    path('housedelete/<int:id>',views.housedelete,name='housedelete'),
    path('fotodelete/<int:id1>/<int:id2>',views.fotodelete,name='fotodelete'),
    path('houseaddimage/<int:id>',views.houseaddimage,name='houseaddimage'),



]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    adress = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtserver = models.CharField(blank=True,max_length=20)
    smtemail = models.CharField(blank=True,max_length=20)
    smtpassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    website = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height=50"/>'.format(self.icon.url))
        image_tag.short_description = 'Image'


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed','Closed')
    )

    name = models.CharField(blank=True,max_length=20)
    email = models.CharField(blank=True, max_length=50)
    icon = models.ImageField(blank=True, upload_to='images/')
    subject = models.CharField(blank=True,max_length=50)
    message = models.CharField(blank=True,max_length=255)
    ip = models.CharField(blank=True,max_length=50)
    note = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactFormu(ModelForm):
    class Meta:
        model=ContactFormMessage
        fields = ['name','email','subject','message']
        widgets ={
            'name' : TextInput(attrs={'class': 'input','placeholder':'İsim Soyisim'}),
            'subject' : TextInput(attrs={'class': 'input','placeholder':'Konu'}),
            'email' : TextInput(attrs={'class': 'input','placeholder':'Email adresi'}),
            'message' : Textarea(attrs={'class': 'input','placeholder':'Mesajınız','rows':'5'}),


        }

class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    adress = models.CharField(blank=True , max_length=150)
    phone = models.CharField(blank=True , max_length=15)
    city = models.CharField(blank=True , max_length=15)
    country = models.CharField(blank=True , max_length=15)
    image = models.ImageField(blank=True , upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return '['+self.user.username+'] '+self.user.first_name+' '+self.user.last_name

    def image_tag(self):
        return mark_safe('<img src="{}" height=50"/>'.format(self.image.url))
        image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
        class Meta:
            model = UserProfile
            fields = ['phone', 'adress', 'city', 'country','image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber=models.IntegerField()
    question = models.CharField(max_length=155)
    answer   = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search' , max_length=100)
    catid = forms.IntegerField()
    cityid = forms.IntegerField()
    priceid = forms.IntegerField()


class SearchForm2(forms.Form):
    query2 = forms.CharField(label='Search2' , max_length=100)
    catid2 = forms.IntegerField()
    cityid2 = forms.IntegerField()
    minbedid = forms.IntegerField()
    districtid = forms.CharField(label='ilce' , max_length=100)
    minbathid = forms.IntegerField()
    minpriceid = forms.IntegerField()
    maxpriceid = forms.IntegerField()
    minareaid = forms.IntegerField()
    maxareaid = forms.IntegerField()



class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30,label='User Name :')
    email = forms.EmailField(max_length=200,label='Email :')
    first_name = forms.CharField(max_length=100 , help_text='First Name',label='First Name :')
    last_name = forms.CharField(max_length=100 , help_text='Last Name',label='Last Name :')

    class Meta:
        model = User
        fields = ('username' , 'email' , 'first_name' , 'last_name' , 'password1' , 'password2' ,)

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.forms import SlugField
from django.http import HttpResponse , request , HttpResponseRedirect
from django.shortcuts import render , redirect

# Create your views here.
from home.models import UserProfile,Setting
from house.models import Category , House , Comment , HouseImageForm , CImages , Images
from user.forms import UserUpdateForm , ProfileUpdateForm
from content.models import Menu , HouseForm
from django.shortcuts import get_object_or_404


def index(request):
    category=Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)

    context = {'profile': profile,
                'category':category,
               }
    return render(request , 'user_profile.html' , context)


def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST , instance=request.user)
        profile_form = ProfileUpdateForm(request.POST , request.FILES , instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request , 'Hesabınız Güncellendi.')
            return redirect('/user')
    else:
        category = Category.objects.all()

        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category ,
            'user_form': user_form ,
            'profile_form': profile_form ,
        }
        return render(request , 'user_update.html' , context)


def change_password(request):

    if request.method == 'POST':
        form = PasswordChangeForm(request.user , request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request , user)
            messages.success(request , 'Şifreniz Başarı ile değiştirildi !')
            return HttpResponseRedirect('/user')
        else:
            messages.warning(request , 'Please correct the error below !')
            return HttpResponseRedirect('/user/password')
    else:
        category=Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request , 'change_password.html' , {'form': form,'category':category})


def comments(request):
    category=Category.objects.all()
    current_user=request.user
    comments=Comment.objects.filter(user_id=current_user.id)
    context={
        'category':category,
        'comments':comments,
    }
    return render(request,'user_comments.html',context)

@login_required(login_url='/login')
def deletecomment(request,id):
    current_user=request.user
    Comment.objects.filter(id=id,user_id=current_user).delete()
    messages.success(request , 'Yorum başarıyla silindi !')
    return HttpResponseRedirect('/user/comments')


@login_required(login_url='/login')
def addhouse(request):
    if request.method=='POST':
        form=HouseForm(request.POST,request.FILES)
        if form.is_valid():
            current_user=request.user
            data=House()
            data.userOwner_id=current_user.id
            data.title=form.cleaned_data['title']
            data.slug=form.cleaned_data['slug']
            data.description=form.cleaned_data['description']
            data.keywords=form.cleaned_data['keywords']
            data.category=form.cleaned_data['category']
            data.price=form.cleaned_data['price']
            data.buildTime=form.cleaned_data['buildTime']
            data.city=form.cleaned_data['city']
            data.district=form.cleaned_data['district']
            data.locationDetail=form.cleaned_data['locationDetail']
            data.area=form.cleaned_data['area']
            data.bedroom=form.cleaned_data['bedroom']
            data.bathroom=form.cleaned_data['bathroom']
            data.garage=form.cleaned_data['garage']
            data.detail=form.cleaned_data['detail']
            data.image=form.cleaned_data['image']
            data.status=False
            data.save()
            messages.success(request,"ilan başarıyla eklendi")
            return HttpResponseRedirect('/user/myhouses')
        else:
            messages.warning(request,'İlan Formu Hata verdi:'+str(form.errors))
            return HttpResponseRedirect('user/myhouses')
    else:
        category=Category.objects.all()
        form=HouseForm()
        setting = Setting.objects.get(pk=1)
        context={
            'setting': setting,
            'category': category,
            'form':form,
        }
    return render(request,'user_addhouse.html',context)


@login_required(login_url='/login')
def houseedit(request,id):
    house= House.objects.get(id=id)
    if request.method=="POST":
        form= HouseForm(request.POST,request.FILES,instance=house)
        if form.is_valid():
            form.save()
            messages.success(request,'Ev Güncellendi')
            return HttpResponseRedirect('/user/myhouses')
        else:
            messages.warning(request,'Ev Form Hatasi : '+str(form.errors))
            return HttpResponseRedirect('/user/houseedit/'+str(id))
    else:
        category = Category.objects.all()
        form=HouseForm(instance=house)
        context={
            'house' : house,
            'form' : form,
            'category' : category,

        }
    return render(request,'user_addhouse.html',context)
@login_required(login_url='/login')
def housedelete(request,id):
    current_user=request.user
    House.objects.filter(id=id,userOwner_id=current_user).delete()
    messages.success(request,"İlan Silindi!")
    return HttpResponseRedirect('/user/myhouses')
@login_required(login_url='/login')
def myhouses(requset):
    category=Category.objects.all()
    menu = Menu.objects.all()
    setting = Setting.objects.get(pk=1)
    current_user=requset.user
    myhouses=House.objects.filter(userOwner_id=current_user.id)

    context = {
        'setting': setting,
        'category':category,
        'menu':menu,
        'myhouses':myhouses,
    }
    return render(requset,'user_myhouses.html',context)

def houseaddimage(request,id):

    if request.method=='POST':
        lasturl=request.META.get('HTTP_REFERER')
        form = HouseImageForm(request.POST,request.FILES)
        if form.is_valid():
            data=Images()
            data.title=form.cleaned_data['title']
            data.house_id=id
            data.image=form.cleaned_data['image']
            data.save()
            messages.success(request,'Fotograf basari ile yuklendi')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request,'Form Error :'+str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        house=House.objects.get(id=id)
        images=Images.objects.filter(house_id=id)
        form=HouseImageForm()
        context = {
            'house': house,
            'images' : images,
            'form' : form,
        }
        return render(request , 'house_fotolar.html' , context)
@login_required(login_url='/login')
def fotodelete(request,id1,id2):
    lasturl = request.META.get('HTTP_REFERER')
    current_user=request.user
    Images.objects.filter(id=id1,house_id=id2).delete()
    messages.success(request,"İlan Silindi!")
    return HttpResponseRedirect(lasturl)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %} Parola Değiştir{% endblock %}
{% block keywords %} İletisim Sayfası anahtar kelimeler {% endblock %}
{% block description %} İletisim Sayfası açıklama {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block baslik %}
    {% include "baslik.html" %}
    {% block link %} iletisim {% endblock %}
{% endblock %}

{% block body %}
    {% load static %}
<style>
th{
    padding: 30px;
    padding-right: 100px;
    text-align:center;
}
td{
    display: flex;
    text-align: center;
    padding: 30px;
}
.button {
    background-color: limegreen;
    color: white;
    font-size: 14px;
    padding: 14px 40px;
    border-radius: 8px;
  transition-duration: 0.4s;
}

.button:hover {
  background-color: black; /* Green */
  color: white;
}
input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
#id_email {
    width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}#id_city {
    width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
</style>
    <section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
        <div class="container">
            <div class="row d-flex align-items-stretch no-gutters">
                <div class="col-md-2 p-4 p-md-5 order-md-last bg-light">
                    {% include 'user_panel.html' %}
                </div>
                <div class="col-md-10 p-4 p-md-5 order-md-last bg-light">

                    <h1>User Change Password</h1>
                    <hr>
                {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" rpşe="alert">
                        {{ message|safe }}
                    </div>
                {% endfor %}
            {% endif %}
                    <form method="post">
                        {% csrf_token %}

                        {% for field in form %}
                            <p>
                                {{ field.label_tag }} <br>
                                {{ field }}
                                {% if field.help_text %}
                                    <small style="color:grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                        <p style="color:red">{{ error }}</p>
                                {% endfor %}

                            </p>
                    {% endfor %}
                    <button type="submit" class="button">Save Changes</button>
                    </form>
                </div>


    </section>

{% endblock %}

user/templates/house_fotolar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ev Galeri</title>
{% load static %}
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <style>
        /* Container needed to position the button. Adjust the width as needed */
.container {
  position: relative;
  width: 50%;
}

/* Make the image responsive */
.container img {
  width: 100%;
  height: auto;
}

/* Style the button and place it in the middle of the container/image */
.container .btn {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  background-color: #555;
  color: white;
  font-size: 16px;
  padding: 12px 24px;
  border: none;
  cursor: pointer;
  border-radius: 5px;
}

.container .btn:hover {
  background-color: black;
}
    </style>
</head>

<body>
<h2>{{ house.title }}</h2>
<hr>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p><input type="hidden" name="house_id" id="id_house_id" value="{{ house_id }}"></p>
    <label for="id_title">Title :</label>
    <p><input type="text" name="title" class="input" placeholder="title" maxlength="50 " id="id_title"></p>
    <label for="id_image">Image : </label>
    <p><input type="file" name="image" class="input" placeholder="image" accept="image/* " id="id_image"></p>
    <button class="primary-btn" type="submit">Upload Image</button>
</form>

<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <div class="container">
    <img src="{{ rs.image.url|default_if_none:'#' }}" height="180">
    <a onclick="return confirm('İlan silinecek! Emin misiniz ?')"
                             href="/user/fotodelete/{{ rs.id }}/{{ house.id }}"><button class="btn" style="background-color: rgba(255,0,0,0.49)">Delete</button></a>
    </div>

{% endfor %}
</body>

</html>

user/templates/user_addhouse.html
{% extends "homebase.html" %}

    {% block title %} {% if house %}İlan Düzenle
    {% else %}Yeni İlan {% endif %}
    {% endblock %}

{% block keywords %} İletisim Sayfası anahtar kelimeler {% endblock %}
{% block description %} İletisim Sayfası açıklama {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>

    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

{% block baslik %}
    {% include "baslik.html" %}
    {% block link %} iletisim {% endblock %}
{% endblock %}

{% block body %}
    {% load static %}
    <style>
        th {
            padding: 5px;

            text-align: center;
        }

        td {

            text-align: left;

            padding: 5px;
        }

        .button {
            background-color: limegreen;
            color: white;
            font-size: 14px;
            padding: 14px 40px;
            border-radius: 8px;
            transition-duration: 0.4s;
        }

        .button:hover {
            background-color: black; /* Green */
            color: white;
        }
    </style>
    <section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
        <div class="container">
            <div class="row d-flex align-items-stretch no-gutters">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" rpşe="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="col-md-12 p-4 p-md-5 order-md-last bg-light">
                    {% if house %}
                    <h3 style="padding: 100px;padding-left: 430px">İlan Düzenle</h3>

                    <img class="icon-adjust" height="300px" width="250px" style="margin:30px 390px" src="{{ house.image.url }}">
                    {% else %}
                        <h3 style="padding: 100px;padding-left: 430px">Yeni İlan</h3>
                    {% endif %}
                    {% load static %}
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ form.media }}
                            {{ form.as_p }}
                        </fieldset>
                        <div class="form-group">
                            <BUTTON class="btn py-3 px-4 btn-primary" TYPE="submit">Kaydet</BUTTON>
                        </div>
                    </form>

                </div>
            </div>


    </section>

{% endblock %}

user/templates/user_myhouses.html
{% extends "homebase.html" %}

{% block title %} İlanlarım {% endblock %}
{% block keywords %} İletisim Sayfası anahtar kelimeler {% endblock %}
{% block description %} İletisim Sayfası açıklama {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block baslik %}
    {% include "baslik.html" %}
    {% block link %} iletisim {% endblock %}
{% endblock %}

{% block body %}
    {% load static %}
    {% load humanize %}
    <style>
        th {
            padding: 5px;

            text-align: center;
        }

        td {

            text-align: left;

            padding: 5px;
        }

        .button {
            background-color: limegreen;
            color: white;
            font-size: 14px;
            padding: 14px 40px;
            border-radius: 8px;
            transition-duration: 0.4s;
        }

        .button:hover {
            background-color: black; /* Green */
            color: white;
        }
    </style>
    <section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
        <div class="container">
            <div class="row d-flex align-items-stretch no-gutters">
                <div class="col-md-2 p-4 p-md-5 order-md-last bg-light">
                    {% include 'user_panel.html' %}
                </div>
                <div class="col-md-10 p-4 p-md-5 order-md-last bg-light">
                    <a class="btn py-3 px-4 btn-primary" style="margin-left: 400px" href="/user/addhouse"> İlan Ver</a>
                    <h1>İlan verilen evler</h1>
                    <hr>
                    <div class="container" >
                        <table class="table-borderless" width="850px" style="font-size: 11px;font-family: Calibri;font-weight: bold">
                            <tr style="font-weight: bolder;font-size: 20px">
                                <th class="text-left">Fotoğraf</th>
                                <th class="text-left">Başlık</th>
                                <th class="text-left">Ev Tipi</th>
                                <th class="text-left">Fiyat</th>
                                <th class="text-left">il</th>
                                <th class="text-left">ilçe</th>
                                <th class="text-left">İlan Tarihi</th>
                                <th class="text-left">Durum</th>
                            </tr>
                            {% for rs in myhouses %}

                                <tr>

                                    <td class="text-left"><img src="{{ rs.image.url }}"
                                                               style="height: 100px;width: 100px"></td>
                                    <td class="text-left">{{ rs.title }}</td>
                                    <td class="text-left">{{ rs.category }}</td>
                                    <td class="text-left">{{ rs.price|intcomma }} ₺</td>
                                    <td class="text-left">{{ rs.get_city_display }}</td>
                                    <td class="text-left">{{ rs.district }}</td>
                                    <td class="text-left">{{ rs.create_at }}</td>
                                    <td class="text-left">{{ rs.status }}</td>

                                </tr>
                                 <th>
                                <td class="text-left"><a class="btn py-3 px-4 btn-primary"
                                                             href="/user/houseedit/{{ rs.id }}">Edit</a></td>
                                 <td class="text-left"><a class="btn py-3 px-4 btn-primary" style="margin-right: 20px;background-color: rgba(165,212,255,0.6)"
                                                          href="javascript:;" onclick="window.open('/user/houseaddimage/{{ rs.id }}','galeri','height=800,width=1000,top=50,left=150')">Resimler</a></td>
                                    <td class="text-left"><a onclick="return confirm('İlan silinecek! Emin misiniz ?')"
                                                             class="btn py-3 px-4 btn-primary" style="background-color: rgba(255,65,64,0.69)" href="/user/housedelete/{{ rs.id }}">Delete</a>
                                    </td>
                                </th>
                            {% endfor %}
                        </table>
                    </div>
                </div>

            </div>
        </div>
        <6*

    </section>

{% endblock %}

user/templates/user_update.html
{% extends "homebase.html" %}

{% block title %} Profil Güncelle {% endblock %}
{% block keywords %} İletisim Sayfası anahtar kelimeler {% endblock %}
{% block description %} İletisim Sayfası açıklama {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block baslik %}
    {% include "baslik.html" %}
    {% block link %} iletisim {% endblock %}
{% endblock %}

{% block body %}
    {% load static %}
<style>
th{
    padding: 30px;
    padding-right: 100px;
    text-align:center;
}
td{
    display: flex;
    text-align: center;
    padding: 30px;
}
.button {
    background-color: limegreen;
    color: white;
    font-size: 14px;
    padding: 14px 40px;
    border-radius: 8px;
  transition-duration: 0.4s;
}

.button:hover {
  background-color: black; /* Green */
  color: white;
}
input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
#id_email {
    width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}#id_city {
    width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
</style>
    <section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
        <div class="container">
            <div class="row d-flex align-items-stretch no-gutters">
                <div class="col-md-2 p-4 p-md-5 order-md-last bg-light">
                    {% include 'user_panel.html' %}
                </div>
                <div class="col-md-10 p-4 p-md-5 order-md-last bg-light">
                    <h1>User Update</h1>
                    <hr>

                    <div class="media">
                    <img src="{{ user.userprofile.image.url }}" style="height: 300px;border-radius: 100px; margin: 20px 100px 30px 300px">
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ user_form.as_p }}
                            {{ profile_form.as_p }}
                        </fieldset>
                        <div class="form-group">
                            <button class="button" type="submit">Update</button>
                        </div>
                    </form>
                </div>

                </div>
            </div>


    </section>

{% endblock %}